### ISSUE TITLE
Pymaid seems incompatible with numpy 1.24.0

### ISSUE THREAD

**Issue by jialumaomao** [navis-org/pymaid#230]
Pymaid now seems to be incompatible with a new version of numpy, 1.24.0. When I try to `pip install python-catmaid` in a fresh virtual environment, I can't  then `import pymaid` in a python shell.  The error it throws is module numpy has no attribute 'bool'. 

(trying to pip install an older version of numpy also doesn't work.)

Would be great to have this working again!

**Comment by schlegelp** [comment]
Hi! I suspect that the incompatibility is due to `navis`, not `pymaid` itself (see https://github.com/navis-org/navis/issues/115). 

I just released `navis` version `1.4.0` which should fix the issues with `numpy`. Please try updating (`pip3 install navis -U`) and let us know if this does the trick! Also make sure to check out the [change log](https://navis.readthedocs.io/en/latest/source/whats_new.html) for other changes.

**Comment by jialumaomao** [comment]
This fixed it! Thanks, everything is working great again.

**Comment by schlegelp** [comment]
Great! I will close the issue then. Feel free to re-open if you run into another problem.
